version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechXProject
  gitServerName: myGithub
  gitUrl: https://github.com/johnlyng
  gitUsername: johnlyng
  gitBranch: main
- name: OpenWeatherClient
  version: "1.0"
  gitServerName: myGithub
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: johnlyng
  gitBranch: main
- name: AvellaClientUtil
  gitServerName: myGithub
  gitUrl: https://github.com/johnlyng
  gitUsername: johnlyng
  gitBranch: main
services:
- serviceName: project.techx.integrations:TestService
  packages:
  - name: TechXProject
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: OpenWeatherClient.REST.openweatherclient_.services:CurrentWeatherData
  packages:
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: pub.string:numericFormat
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: project.techx.integrations:myFirstEdgeFlow
  packages:
  - name: TechXProject
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
