version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechXProject
  gitServerName: myGithub
  gitUrl: https://github.com/johnlyng
  gitUsername: johnlyng
  gitBranch: main
services:
- serviceName: project.techx.integrations:myFirstEdgeFlow
  packages:
  - name: TechXProject
    version: "1.0"
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
